name: Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: "The branch, tag, or SHA to run on"
        required: false
        default: ""
      debug:
        type: boolean
        description: Run with debugging enabled
        required: false
        default: false

jobs:
  streamer-amd64:
    name: Streamer (amd64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt -y install protobuf-compiler
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build cedana-image-streamer
        run: |
          make

      - name: Persist cedana-image-streamer
        id: persist-cedana-image-streamer
        uses: actions/upload-artifact@v4
        with:
          name: streamer
          path: target/release/cedana-image-streamer

