name: Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: "The branch, tag, or SHA to run on"
        required: false
        default: ""
      debug:
        type: boolean
        description: Run with debugging enabled
        required: false
        default: false

jobs:
  streamer:
    name: Streamer
    runs-on: runs-on=${{github.run_id}}/runner=m7-large-${{ matrix.arch }}/extras=s3-cache
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          # - arm64
    steps:
      - uses: runs-on/action@v1
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt -y install protobuf-compiler
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Load from cache
        uses: runs-on/cache@v4
        with:
          path: target/release
          key: streamer-${{ matrix.arch }}

      - name: Build cedana-image-streamer
        run: |
          make

      - name: Upload binary
        id: upload-binary
        uses: actions/upload-artifact@v4
        with:
          name: streamer-${{ matrix.arch }}
          path: target/release/cedana-image-streamer

