name: Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_build:
        type: boolean
        description: "Run build with debugging enabled"
        required: false
        default: false
      debug_test:
        type: boolean
        description: "Run tests with debugging enabled"
        required: false
        default: false
      debug_publish:
        type: boolean
        description: "Run publish with debugging enabled"
        required: false
        default: false

concurrency:
  group: cedana-image-streamer-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_build }}

  download:
    name: Download
    uses: cedana/cedana/.github/workflows/download.yml@feature/ced-1034-run-all-benchmarks-on-all-repos-involved
    secrets: inherit
    with:
      cedana_version: feature/ced-1034-run-all-benchmarks-on-all-repos-involved
      gpu_version: feature/ced-1034-run-all-benchmarks-on-all-repos-involved

  test:
    name: Test
    uses: cedana/cedana/.github/workflows/test.yml@feature/ced-1034-run-all-benchmarks-on-all-repos-involved
    needs: [build, download]
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_test }}
      streamer: true
      gpu: true
      cpu: false

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    needs: build
    secrets: inherit
    with:
      debug: ${{ startsWith(github.event_name, 'workflow') && inputs.debug_publish }}
      cloudsmith: true
      cloudsmith_repo: cedana-image-streamer-alpha
      post_summary: false
